CREATE TABLE IF NOT EXISTS sessions (
    id SERIAL PRIMARY KEY,
    access_token TEXT NOT NULL,
    user_agent TEXT,
    ip VARCHAR,
    revoked BOOL DEFAULT FALSE,
    user_id INTEGER NOT NULL,
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
