CREATE TABLE IF NOT EXISTS teams (
  id SERIAL PRIMARY KEY,
  name VARCHAR NOT NULL UNIQUE,
  price DECIMAL(15, 2) NOT NULL,
  owner VARCHAR NOT NULL,
  protocol INTEGER NOT NULL UNIQUE,
  date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
