CREATE TABLE IF NOT EXISTS players (
  id SERIAL PRIMARY KEY,
  name VARCHAR NOT NULL,
  language VARCHAR(255) DEFAULT 'pt-br'::CHARACTER VARYING,
  uuid UUID NOT NULL UNIQUE DEFAULT uuid_generate_v4(),
  status BOOL DEFAULT FALSE,
  team_id INTEGER NOT NULL,
  CONSTRAINT fk_team_id FOREIGN KEY (team_id) REFERENCES teams (id) ON DELETE CASCADE
);
